### ISSUE TITLE
Can't run mikutter.rb

### ISSUE THREAD

**Issue by JPRuehmann** [mikutter/mikutter#2]
Hello
If I try to run mikutter.rb from its folder, Iget the following output but the Program will not show up.

./mikutter.rb
/usr/lib/i386-linux-gnu/ruby/2.3.0/continuation.so: warning: callcc is obsolete; use Fiber instead
Warning: obsolete msgid exists.
         #~ msgid "表示しないイベント"
Warning: obsolete msgid exists.
         #~ msgstr "表示せえへんイベント"
Warning: obsolete msgid exists.
         #~ msgid "以下の全てのイベント"
Warning: obsolete msgid exists.
         #~ msgstr "以下の全てのイベント"
Warning: obsolete msgid exists.
         #~ msgid "（読み込み中）"
Warning: obsolete msgid exists.
         #~ msgstr "（読み込み中）"
Warning: obsolete msgid exists.
         #~ msgid "URLの取得に失敗"
Warning: obsolete msgid exists.
         #~ msgstr "なんかうまいこといかんかった"
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- totoridipjp (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /home/ruehmann/mikutter/core/plugin/photo_support/photo_support.rb:4:in `<top (required)>'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:155:in`load'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:155:in `load'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:98:in`block in load_all'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:38:in `block in each_spec'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:33:in`each'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:33:in `each'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:36:in`each_spec'
        from /home/ruehmann/mikutter/core/miquire_plugin.rb:96:in `load_all'
        from /home/ruehmann/mikutter/core/boot/load_plugin.rb:10:in`<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from /home/ruehmann/mikutter/core/miquire.rb:98:in `miquire_original_require'
        from /home/ruehmann/mikutter/core/miquire.rb:95:in`file_or_directory_require'
        from /home/ruehmann/mikutter/core/miquire.rb:76:in `block in miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in`each'
        from /home/ruehmann/mikutter/core/miquire.rb:75:in `miquire'
        from /home/ruehmann/mikutter/core/miquire.rb:18:in`miquire'
        from ./mikutter.rb:38:in `<main>'

I am using Kubuntu 16.04 LTS
Thanks,

**Comment by cosmo0920** [comment]
It seems that `totoridipjp` is not installed in your environment.

The following command shows `totoridipjp`?

```
$ gem list | grep totoridipjp
```

**Comment by JPRuehmann** [comment]
thanks, worked.

**Comment by cosmo0920** [comment]
Yay! :tada:
