### ISSUE TITLE
Mikutter chrashes after some Hours

### ISSUE THREAD

**Issue by JPRuehmann** [mikutter/mikutter#4]
Hello
Since the last Update 09.10.2016) Mikutter Crashes after some hours.
The System say that it can´t create a Report since there is no Memory left
I have 16GB of Memory and Kubuntu 16.04 LTS.
Thanks

**Comment by JPRuehmann** [comment]
Hello
Here is the Output of the Commandline for mikutter &> mikutter.txt
[mikuter.txt](https://github.com/mikutter/mikutter/files/524773/mikuter.txt)
Hope this will help a little.
Thanks,

**Comment by cosmo0920** [comment]
> (mikutter.rb:21738): GLib-ERROR **: /build/glib2.0-8EA4QF/glib2.0-2.48.1/./glib/gmem.c:100: failed to allocate 3240000 bytes

3240000 / 1024.0 / 1024.0 => 3.08990478515625
It seems that glib2, which is mikutter dependent gem, fails to allocate about 3GB memory.

Your computer has enough free memory when running mikutter?

**Comment by JPRuehmann** [comment]
I have this Problem with two Computers,
1 have 16GB
1 have 2G
Both are 32Bit.
But what the Devil Mikutter is wanting 3GB for, I ask you?
That will be at least 3time the Space of the Complete OS without Mikutter.
Thanks,

**Comment by cosmo0920** [comment]
Could you get mikutter's memory consumption, or amount of memory usage entire system?
I suspect that mikutter or its dependent gems have not revealed memory leak.

**Comment by JPRuehmann** [comment]
mikutter itself uses 204KB and is stable
but the Rubu Part starts with 56MB then goes to 168MB in minutes and then in hours to above 2.5 GB
The System itself takes about 500MB of RAM and 500MB Swap stable.

**Comment by cosmo0920** [comment]
Thank you for your feedback.
mikutter author started to investigate this memory leak like issue (Japanese): https://twitter.com/toshi_a/status/786680945063686149
Let's wait for his investigate results and fixes.

**Comment by JPRuehmann** [comment]
will there be a resolution in the near future?

**Comment by osak** [comment]
Unfortunately this problem is unlikely resolved in the near future, but I'm investigating this problem.
@JPRuehmann Do you use any 3rd-party plugins? If any, could you provide the list of those plugin names? Some users also report high-memory usage problem but @toshia said he couldn't reproduce it, thus I suspect that a particular plugin causes this error.

**Comment by JPRuehmann** [comment]
The only Plugin I am using is https://github.com/moguno/mikutter-subparts-image.

**Comment by JPRuehmann** [comment]
Seems that is the Problem, after disabling the Plugin it works well, after 30h it uses still only 2MB of ram.
But there is no one that works on that Plugin anymore I think and the Funktion of showing images is very important I think.
Thanks

**Comment by osak** [comment]
Thanks for your report! Our hypothesis is that mikutter is leaking some amount of memory regardless of mikutter-subparts-image plugin installed or not, however, that plugin dramatically boosts the extent of the leakage. We are working on possible fixes and the next stable release will include some of them.

**Comment by JPRuehmann** [comment]
I think that it would be best to integrate the image display function yourself, since the Plugin is dead, the fuction is cruciable I think and it would be very lovely if it gets translated too.
Thanks, till then

**Comment by JPRuehmann** [comment]
The latest update does´nt change this Problem.

**Comment by JPRuehmann** [comment]
everythings fine.
